site_name: Creating a Personal Webpage
nav:
  - Home: index.md
  - Create Github Account: create-github.md
  - Basics: basics.md
  - Basic Customization: basic-customization.md
  - Next Steps: next-steps.md
theme: 'material'
markdown_extensions:  
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences